# -*- coding: utf-8 -*-
"""Demo_Generate_Images_With_DALL·E_2_and_the_OpenAI_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xofQnJMLOqf4KYTVmQOGm3drvJuQgu12

# **Demo Generate Images With DALL·E 2 and the OpenAI API**

# **Description**
In this project, you will learn how to use LangChain, an open-source framework that allows you to build applications with large language models (LLMs) such as OpenAI’s DALL-E.

# **Steps to perform:**

1. Setup the environment
2. Generate image from the text
3. Display the generated images

# **Step 1: Setup the environment**
"""

import os
import openai
from google.colab import userdata

openai.api_key  = userdata.get('OPENAI_API_KEY')

"""# **Step 2:  Generate image from the text**"""

Text_PROMPT = input("Enter a Text : ")



Image_response = openai.Image.create(
    prompt=Text_PROMPT,
    n=1,
    size="256x256",
)

print(Image_response["data"][0]["url"])

print(Image_response)

"""**Observation:**
- Click on the above link to locate the image you requested

# **Conclusion**
By the end of this project, you will have gained experience in how to use LangChain and OpenAI to generate images from text.
"""