# -*- coding: utf-8 -*-
"""Demo_Few_shot_prompting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vC1bedFC2NqHLFjaxJU9h_ue3tp9zmY8

# __Demo: Few-Shot Prompting with OpenAI__

## __Steps to Perform:__
Step 1: Set up the OpenAI API Key

Step 2: Define a Function to Get Completion

Step 3: Define Your Prompt

### __Step 1: Set up the OpenAI API Key__

- The code imports the necessary libraries.
- The __os__ is used for interacting with the operating system, and __openai__ is the library required to work with OpenAI's API.
"""

import os
import openai
from google.colab import userdata


openai.api_key  = userdata.get('OPENAI_API_KEY')



"""### __Step 2: Define a Function to Get Completion__
The __get_completion__ function is responsible for sending a prompt to the OpenAI model and receiving its response.

__Parameters:__

- __prompt__: It is the text input for which the model will generate a completion.
- __model__: The gpt-3.5-turbo model is used to perform the tasks.

The __openai.ChatCompletion.create__ function is used to send a request to the OpenAI API.

This request includes the model, the input messages (formatted as a list of dictionaries with user roles and content), and a temperature setting.
"""

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message.content

"""### __Step 3: Define Your Prompts__
- The prompt consists of several pieces of customer feedback, each followed by a classification (Positive, Negative, or Neutral).
- These examples serve to teach the model what kind of output is expected.
- The final feedback statement is the new instance for which the classification is sought.
"""

prompt = """
Feedback: "I loved the quick service and friendly staff."
Classification: Great we are delighed to have a Positive sentiment
Score : 0.9

Feedback: "The product did not meet my expectations."
Classification: Oops, we are afraid its a Negative sentiment
Score : 0.2

Feedback: "I am not sure if this is the right product for me."
Classification: We will try to improve and satisfy you next time as its a Neutral sentiment.
Score : 0.5

Feedback: "Your customer support was helpful, very satisfied."
Classification:
Score:
"""
response = get_completion(prompt)
print(response)

prompt = """

Q: What is the capital of Italy?
A: "Imperium Romanum in aeternum stabit.", Rome

Q: What is the capital of France?
A: "L'Empire romain devrait tenir pour l'éternité.", Paris

Q: What is the capital of Japan?
A: "日本は永遠に生き続けるべきです。", Tokyo

Q: What is the capital of Germany?
A: "Das Deutsche Reich sollte für immer bestehen.", Berlin

Q: What is the capital of Brazil?
A: "O Império Brasileiro deve durar para sempre.", Brasília

Q: What is the capital of USA?
A:

"""
response = get_completion(prompt)
print(response)

prompt = """
Task: Generate a subject line for the following emails.

Email: "Thank you for your purchase! Your order has been shipped and will arrive in 3-5 business days."
Subject: "Your Order Has been Shipped! Hurray"

Email: "We noticed you left items in your cart. Don’t miss out on these great deals!"
Subject: "Don’t Forget: Items Waiting in Your Cart!"

Email: "We’ve just launched a new product line. Check out our latest arrivals and get 10% off your first purchase."
Subject: "Explore Our New Arrivals & Enjoy 10% Off!"

Email: "Your subscription is about to expire. Renew now to continue enjoying our services."
Subject:
"""
response = get_completion(prompt)
print(response)

"""In this few-shot scenario, the model uses the provided examples to understand the context and criteria for classification, applying that understanding to classify new, unseen feedback. This is particularly useful for more subjective tasks like sentiment analysis, where context and nuance play significant roles."""