# -*- coding: utf-8 -*-
"""Demo_Tree_of_Thoughts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJ3E5dPFdt2mZK4FYEB3de-D3nU28y-L

# __Demo: Tree of Thought Prompting with OpenAI__


## __Steps to Perform:__
Step 1: Set up the OpenAI API Key

Step 2: Define a Function to Get Completion

Step 3: Define Your Prompts

### __Step 1: Set up the OpenAI API Key__
- Import the required libraries and set up the OpenAI API key.
"""

import os
import openai
from google.colab import userdata

openai.api_key  = userdata.get('OPENAI_API_KEY')

"""### __Step 2: Define a Function to Get Completion__
- Construct a message with the user's prompt.
- Call the __openai.ChatCompletion.create__ method to get a response from the model.
- The temperature parameter is set to __0__ for deterministic (non-random) responses.
"""

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message.content

"""### __Step 3: Define Your Prompts__
- Provide a series of prompts that guide the model through a tree of thought.
- Call __get_completion__ to get a response from the AI model.
- Print both the prompt and the AI-generated response.
"""

prompt = """
Solve the problem: A farmer has 100 meters of fencing and wants to enclose the maximum area for his rectangular field. What should the dimensions be?

Let's think about this in a few ways:

1. If the field is a square, each side would be 100 / 4 = 25 meters. The area would be 25 * 25 = 625 square meters.

2. What if the field is not a square? Let's try a 2:1 ratio. The lengths would be 40 and 20 meters. The area would be 40 * 20 = 800 square meters.

3. Are there any other ratios that might give a larger area than a square or a 2:1 rectangle?

Considering these options, the best dimensions for the maximum area are:
"""
response = get_completion(prompt)
print("AI Response:")
print(response)

"""
Analyze the output of the model. If the output is not satisfactory, you can refine the prompts and repeat the process."""