# -*- coding: utf-8 -*-
"""Demo_Zero_Shot_Prompting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o93NPCuIjiMN33jvJ7FHI54VPwbaERan

# __Demo: Zero-Shot Prompting with OpenAI__

## __Steps to Perform:__
Step 1: Set up the OpenAI API Key

Step 2: Define a Function to Get Completion

Step 3: Define Your Prompt

### __Step 1: Set up the OpenAI API Key__
- The code imports the necessary libraries.
- The **os** is used for interacting with the operating system, and __openai__ is the library required to work with OpenAI's API.
"""

import os
import openai
from google.colab import userdata

openai.api_key  = userdata.get('OPENAI_API_KEY')

# local environment variable loading
# openai.api_key  = os.getenv('OPENAI_API_KEY')

# Adding API key value directly
# openai.api_key  = "sk-klpk-R_jslfyilZyp1kdci7-y0i32VlcXkmbbbMT3BlbkFJHDrMsmVhYGcR123456XQFAeNAZqHgVA-6mYWEVTbb2_jSLAMPDcpaW09QUA"

"""### __Step 2: Define a Function to Get Completion__
The __get_completion__ function is responsible for sending a prompt to the OpenAI model and receiving its response.

__Parameters:__
  - __prompt__: It is the text input for which the model will generate a completion.
  -  __model__: The gpt-3.5-turbo model is used to perform the tasks.

The __openai.chat.completions.create__ function is used to send a request to the OpenAI API.
- This request includes the model, the input messages (formatted as a list of dictionaries with user roles and content), and a temperature setting.
"""

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]

    response = openai.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.5,
        max_tokens=512
    )
    return response.choices[0].message.content

"""### __Step 3: Define Your Prompt__
- The prompt variable is defined with a simple translation task.
"""

prompt = "Explain Zero Shot Prompting"
response = get_completion(prompt)

print(response)

prompt = "What is the capital of USA?"
response = get_completion(prompt)

print(response)

